# Generated by Django 5.0.1 on 2024-01-14 16:50

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0003_attachment_created_by_attachment_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampanya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active?')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Kampanya Başlığı')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Öncelik Sırası')),
                ('slug', models.CharField(blank=True, max_length=500, null=True, verbose_name='Slug')),
                ('summary', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2500, null=True, verbose_name='Özet')),
                ('details', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1500, null=True, verbose_name='Detay')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Start At')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='End At')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kampanya_banner', to='attachment.attachment', verbose_name='Kampanya Banner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deleted_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaigns',
                'verbose_name_plural': 'Campaign',
                'db_table': 'kampanya',
                'ordering': ['-created_at'],
            },
        ),
    ]
