# Generated by Django 5.0.1 on 2024-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Name'),
        ),
    ]
