# Generated by Django 5.0.1 on 2024-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_frontend_site_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontend',
            options={'ordering': ['-created_at'], 'verbose_name': 'Frontend', 'verbose_name_plural': 'Frontend'},
        ),
        migrations.AlterModelTable(
            name='frontend',
            table='frontend',
        ),
    ]
