# Generated by Django 5.0.1 on 2024-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_frontend_options_alter_frontend_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontend',
            old_name='facebook_address',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='frontend',
            old_name='instagram_address',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='frontend',
            old_name='linkedin_address',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='frontend',
            old_name='tiktok_address',
            new_name='tiktok',
        ),
        migrations.RenameField(
            model_name='frontend',
            old_name='youtube_address',
            new_name='twitter',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='acente_destek_hatti',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='call_logo',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='garanti_bank_logo',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='garanti_bank_white_logo',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='hasar_iletisim_hatti',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='iyzico_logo',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='iyzico_payment_cards',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='mastercard_logo',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='sigorta_acentesi_misiniz',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='visa_logo',
        ),
        migrations.AddField(
            model_name='frontend',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
