# Generated by Django 5.0.1 on 2024-01-14 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Car Marks',
                'verbose_name_plural': 'Car Marks',
                'db_table': 'car_mark',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'db_table': 'car_model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'db_table': 'vehicle_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Araba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active?')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_register_seri', models.CharField(blank=True, max_length=2, null=True)),
                ('vehicle_register_no', models.CharField(blank=True, max_length=6, null=True)),
                ('car_model_year', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('Manuel', 'Manuel'), ('Automatic', 'Automatic'), ('Semi Automatic', 'Semi Automatic'), ('Continuously Variable', 'Continuously Variable'), ('Dual Clutch', 'Dual Clutch')], max_length=50, null=True)),
                ('fuel', models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Bio Diesel', 'Bio Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=50, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('cost_of_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('km_min_constraint', models.IntegerField(blank=True, null=True)),
                ('age_min_constraint', models.IntegerField(blank=True, null=True)),
                ('licence_min_constraint', models.IntegerField(blank=True, null=True)),
                ('payment_constraint', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash')], default='Credit Card', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deleted_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Customer Car',
                'verbose_name_plural': 'Customer Cars',
                'db_table': 'customer_car',
                'ordering': ['pk'],
            },
        ),
    ]
