# Generated by Django 5.0.1 on 2024-01-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araba', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='araba',
            options={'ordering': ['pk'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelTable(
            name='araba',
            table='vehicle',
        ),
    ]
