# Generated by Django 5.0.1 on 2024-01-14 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0003_attachment_created_by_attachment_deleted_by_and_more'),
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active?')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis Adı')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis Kurumsal Eposta')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis Kurumsal Telefon')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Ofis Kodu')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis Facebook Adresi')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis Twitter Adresi')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis İnstagram Adresi')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ofis Tiktok Adresi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deleted_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('il', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.il')),
                ('ilce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.ilce')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachment.attachment')),
                ('mahallekoy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.mahallekoy')),
                ('sokak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.sokak')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ofice',
                'verbose_name_plural': 'Ofices',
                'db_table': 'ofis',
                'ordering': ['-created_at'],
            },
        ),
    ]
