# Generated by Django 4.2.7 on 2023-11-27 21:16

import attachment.models
from django.db import migrations, models
import utils.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('webp', models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/webp')),
                ('thumbnail', models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/thumbnails')),
                ('original', models.FileField(blank=True, max_length=500, null=True, upload_to=attachment.models.get_file_path, validators=[utils.util.validate_file_extension])),
                ('mime', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachment',
                'ordering': ['-pk'],
            },
        ),
    ]
