# Generated by Django 4.2.7 on 2023-11-27 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=550, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tckn', models.CharField(blank=True, default='00000000000', max_length=11, null=True)),
                ('kvkk', models.BooleanField(blank=True, default=False, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('role', models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('editor', 'editor'), ('call_center', 'call_center'), ('broker', 'broker'), ('oto_kiralama', 'oto_kiralama'), ('oto_kurtarma', 'oto_kurtarma'), ('oto_lastikçi', 'oto_lastikci')], default='editor', max_length=255)),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_mobile_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('guvenassist_sms_allowed', models.BooleanField(blank=True, default=True, null=True)),
                ('guvenassist_email_allowed', models.BooleanField(blank=True, default=True, null=True)),
                ('guvenassist_phone_allowed', models.BooleanField(blank=True, default=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachment.attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['pk'],
            },
        ),
    ]
