# Generated by Django 4.2.7 on 2023-12-06 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_kvkk_user_kvvk_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acente_temsilcisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_agency_contact', to=settings.AUTH_USER_MODEL, verbose_name='Agency Contact'),
        ),
    ]
