# Generated by Django 4.2.7 on 2023-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_acente_temsilcisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mss_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
