# Generated by Django 5.0.1 on 2024-01-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_carduserkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('editor', 'editor'), ('customer', 'customer')], default='customer', max_length=255),
        ),
    ]
